### ISSUE TITLE
code for day 2 project (tip calculator)

### ISSUE THREAD

**Issue by realblazegunner** [realblazegunner/pyhton-day2-project#1]
in this project we are going to maek a tip calculator that will in ask how many people we want to split the bill and how much tip we want to give (in percent) and it will show you how much money you have to pay.

**Comment by ghost** [comment]
print("Welcome to the tip calculator !!")
total_bill=float(input("What is the total bill ? "))
tip=float(input("What percentage tip would you like to give ? "))
people=int(input("How many people to split the bill ? "))
your_bill=total_bill/people
you_pay=round(( your_bill * (tip/100)) + your_bill,2)
print(f"You have to pay : {you_pay}")
